// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app_workflow.proto3

package workflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import any "github.com/golang/protobuf/ptypes/any"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AppRequest struct {
	AppName              string            `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	AppVersion           string            `protobuf:"bytes,2,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	Fields               []*Field          `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Environment          map[string]string `protobuf:"bytes,4,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Action               string            `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AppRequest) Reset()         { *m = AppRequest{} }
func (m *AppRequest) String() string { return proto.CompactTextString(m) }
func (*AppRequest) ProtoMessage()    {}
func (*AppRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_workflow_092411e0f67d38bb, []int{0}
}
func (m *AppRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppRequest.Unmarshal(m, b)
}
func (m *AppRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppRequest.Marshal(b, m, deterministic)
}
func (dst *AppRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppRequest.Merge(dst, src)
}
func (m *AppRequest) XXX_Size() int {
	return xxx_messageInfo_AppRequest.Size(m)
}
func (m *AppRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AppRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AppRequest proto.InternalMessageInfo

func (m *AppRequest) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *AppRequest) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func (m *AppRequest) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *AppRequest) GetEnvironment() map[string]string {
	if m != nil {
		return m.Environment
	}
	return nil
}

func (m *AppRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

type AppResponse struct {
	Fields               []*Field `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	Raw                  *any.Any `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppResponse) Reset()         { *m = AppResponse{} }
func (m *AppResponse) String() string { return proto.CompactTextString(m) }
func (*AppResponse) ProtoMessage()    {}
func (*AppResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_workflow_092411e0f67d38bb, []int{1}
}
func (m *AppResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppResponse.Unmarshal(m, b)
}
func (m *AppResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppResponse.Marshal(b, m, deterministic)
}
func (dst *AppResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppResponse.Merge(dst, src)
}
func (m *AppResponse) XXX_Size() int {
	return xxx_messageInfo_AppResponse.Size(m)
}
func (m *AppResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AppResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AppResponse proto.InternalMessageInfo

func (m *AppResponse) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *AppResponse) GetRaw() *any.Any {
	if m != nil {
		return m.Raw
	}
	return nil
}

type App struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Price                float32  `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_workflow_092411e0f67d38bb, []int{2}
}
func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (dst *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(dst, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *App) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *App) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func init() {
	proto.RegisterType((*AppRequest)(nil), "AppRequest")
	proto.RegisterMapType((map[string]string)(nil), "AppRequest.EnvironmentEntry")
	proto.RegisterType((*AppResponse)(nil), "AppResponse")
	proto.RegisterType((*App)(nil), "App")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppWorkflowClient is the client API for AppWorkflow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppWorkflowClient interface {
	Invoke(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*AppResponse, error)
	List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (AppWorkflow_ListClient, error)
}

type appWorkflowClient struct {
	cc *grpc.ClientConn
}

func NewAppWorkflowClient(cc *grpc.ClientConn) AppWorkflowClient {
	return &appWorkflowClient{cc}
}

func (c *appWorkflowClient) Invoke(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*AppResponse, error) {
	out := new(AppResponse)
	err := c.cc.Invoke(ctx, "/AppWorkflow/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appWorkflowClient) List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (AppWorkflow_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AppWorkflow_serviceDesc.Streams[0], "/AppWorkflow/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &appWorkflowListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AppWorkflow_ListClient interface {
	Recv() (*App, error)
	grpc.ClientStream
}

type appWorkflowListClient struct {
	grpc.ClientStream
}

func (x *appWorkflowListClient) Recv() (*App, error) {
	m := new(App)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AppWorkflowServer is the server API for AppWorkflow service.
type AppWorkflowServer interface {
	Invoke(context.Context, *AppRequest) (*AppResponse, error)
	List(*empty.Empty, AppWorkflow_ListServer) error
}

func RegisterAppWorkflowServer(s *grpc.Server, srv AppWorkflowServer) {
	s.RegisterService(&_AppWorkflow_serviceDesc, srv)
}

func _AppWorkflow_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppWorkflowServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AppWorkflow/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppWorkflowServer).Invoke(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AppWorkflow_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AppWorkflowServer).List(m, &appWorkflowListServer{stream})
}

type AppWorkflow_ListServer interface {
	Send(*App) error
	grpc.ServerStream
}

type appWorkflowListServer struct {
	grpc.ServerStream
}

func (x *appWorkflowListServer) Send(m *App) error {
	return x.ServerStream.SendMsg(m)
}

var _AppWorkflow_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AppWorkflow",
	HandlerType: (*AppWorkflowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _AppWorkflow_Invoke_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _AppWorkflow_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "app_workflow.proto3",
}

func init() { proto.RegisterFile("app_workflow.proto3", fileDescriptor_app_workflow_092411e0f67d38bb) }

var fileDescriptor_app_workflow_092411e0f67d38bb = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xcf, 0x6b, 0xe2, 0x40,
	0x14, 0x36, 0x3f, 0x8c, 0xbb, 0x2f, 0xbb, 0x20, 0xb3, 0x22, 0x31, 0xbb, 0xec, 0x4a, 0x60, 0x97,
	0x9c, 0xc6, 0xc5, 0x5e, 0x4a, 0x0f, 0x82, 0x07, 0x0b, 0x42, 0xe9, 0x21, 0xd0, 0xf6, 0xd6, 0x32,
	0xda, 0xa7, 0x04, 0x93, 0x99, 0x69, 0x12, 0x23, 0xb9, 0xf5, 0x4f, 0x2f, 0x33, 0x89, 0x98, 0xda,
	0xde, 0xe6, 0x9b, 0xef, 0xcd, 0x7c, 0x3f, 0x78, 0xf0, 0x83, 0x49, 0xf9, 0x74, 0x10, 0xd9, 0x6e,
	0x93, 0x88, 0x03, 0x95, 0x99, 0x28, 0xc4, 0x85, 0xff, 0x7d, 0x13, 0x63, 0xf2, 0x9c, 0x1f, 0xe1,
	0x68, 0x2b, 0xc4, 0x36, 0xc1, 0x89, 0x86, 0xab, 0xfd, 0x66, 0xc2, 0x78, 0x55, 0x73, 0xfe, 0xcf,
	0x73, 0x0a, 0x53, 0x59, 0x34, 0x64, 0xf0, 0x6a, 0x02, 0xcc, 0xa5, 0x8c, 0xf0, 0x65, 0x8f, 0x79,
	0x41, 0x46, 0xf0, 0x45, 0x89, 0x71, 0x96, 0xa2, 0x67, 0x8c, 0x8d, 0xf0, 0x6b, 0xd4, 0x63, 0x52,
	0xde, 0xb2, 0x14, 0xc9, 0x1f, 0x70, 0x15, 0x55, 0x62, 0x96, 0xc7, 0x82, 0x7b, 0xa6, 0x66, 0x81,
	0x49, 0x79, 0x5f, 0xdf, 0x90, 0xdf, 0xe0, 0xd4, 0x9e, 0x3c, 0x6b, 0x6c, 0x85, 0xee, 0xd4, 0xa1,
	0xd7, 0x0a, 0x46, 0xcd, 0x2d, 0x99, 0x81, 0x8b, 0xbc, 0x8c, 0x33, 0xc1, 0x53, 0xe4, 0x85, 0x67,
	0xeb, 0xa1, 0x5f, 0xf4, 0xa4, 0x4e, 0x17, 0x27, 0x7a, 0xc1, 0x8b, 0xac, 0x8a, 0xda, 0x0f, 0xc8,
	0x10, 0x1c, 0xb6, 0x2e, 0x94, 0x76, 0x57, 0x6b, 0x37, 0xc8, 0x9f, 0x41, 0xff, 0xfc, 0x21, 0xe9,
	0x83, 0xb5, 0xc3, 0xaa, 0x89, 0xa0, 0x8e, 0x64, 0x00, 0xdd, 0x92, 0x25, 0x7b, 0x6c, 0x8c, 0xd7,
	0xe0, 0xca, 0xbc, 0x34, 0x82, 0x3b, 0x70, 0xb5, 0x87, 0x5c, 0x0a, 0x9e, 0x63, 0x2b, 0x86, 0xf1,
	0x69, 0x8c, 0x7f, 0x60, 0x65, 0xec, 0xa0, 0xbf, 0x71, 0xa7, 0x03, 0x5a, 0x97, 0x4b, 0x8f, 0xe5,
	0xd2, 0x39, 0xaf, 0x22, 0x35, 0x10, 0x2c, 0xc1, 0x9a, 0x4b, 0x49, 0x08, 0xd8, 0xad, 0x36, 0xf5,
	0x99, 0x78, 0xd0, 0x7b, 0x5f, 0xe3, 0x11, 0x2a, 0x97, 0x32, 0x8b, 0xd7, 0xe8, 0x59, 0x63, 0x23,
	0x34, 0xa3, 0x1a, 0x4c, 0x1f, 0xb5, 0xc3, 0x87, 0x66, 0x03, 0xc8, 0x5f, 0x70, 0x96, 0xbc, 0x14,
	0x3b, 0x24, 0x6e, 0xab, 0x3d, 0xff, 0x1b, 0x6d, 0xc5, 0x08, 0x3a, 0x24, 0x04, 0xfb, 0x26, 0xce,
	0x0b, 0x32, 0xfc, 0xe0, 0x71, 0xa1, 0x16, 0xc0, 0xb7, 0xd5, 0x7c, 0xd0, 0xf9, 0x6f, 0xac, 0x9c,
	0x7a, 0x89, 0xde, 0x02, 0x00, 0x00, 0xff, 0xff, 0x68, 0x06, 0xb8, 0x34, 0x69, 0x02, 0x00, 0x00,
}
