// Code generated by protoc-gen-go. DO NOT EDIT.
// source: content_workflow.proto3

package workflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ContentType int32

const (
	ContentType_MARKETING_LANDING_PAGE ContentType = 0
)

var ContentType_name = map[int32]string{
	0: "MARKETING_LANDING_PAGE",
}
var ContentType_value = map[string]int32{
	"MARKETING_LANDING_PAGE": 0,
}

func (x ContentType) String() string {
	return proto.EnumName(ContentType_name, int32(x))
}
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_content_workflow_f08798b923403014, []int{0}
}

type ContentRequest struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 ContentType `protobuf:"varint,3,opt,name=type,proto3,enum=ContentType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ContentRequest) Reset()         { *m = ContentRequest{} }
func (m *ContentRequest) String() string { return proto.CompactTextString(m) }
func (*ContentRequest) ProtoMessage()    {}
func (*ContentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_workflow_f08798b923403014, []int{0}
}
func (m *ContentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentRequest.Unmarshal(m, b)
}
func (m *ContentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentRequest.Marshal(b, m, deterministic)
}
func (dst *ContentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentRequest.Merge(dst, src)
}
func (m *ContentRequest) XXX_Size() int {
	return xxx_messageInfo_ContentRequest.Size(m)
}
func (m *ContentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContentRequest proto.InternalMessageInfo

func (m *ContentRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ContentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ContentRequest) GetType() ContentType {
	if m != nil {
		return m.Type
	}
	return ContentType_MARKETING_LANDING_PAGE
}

type ContentResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ContentUrl           string   `protobuf:"bytes,3,opt,name=content_url,json=contentUrl,proto3" json:"content_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContentResponse) Reset()         { *m = ContentResponse{} }
func (m *ContentResponse) String() string { return proto.CompactTextString(m) }
func (*ContentResponse) ProtoMessage()    {}
func (*ContentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_content_workflow_f08798b923403014, []int{1}
}
func (m *ContentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentResponse.Unmarshal(m, b)
}
func (m *ContentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentResponse.Marshal(b, m, deterministic)
}
func (dst *ContentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentResponse.Merge(dst, src)
}
func (m *ContentResponse) XXX_Size() int {
	return xxx_messageInfo_ContentResponse.Size(m)
}
func (m *ContentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContentResponse proto.InternalMessageInfo

func (m *ContentResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ContentResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ContentResponse) GetContentUrl() string {
	if m != nil {
		return m.ContentUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*ContentRequest)(nil), "ContentRequest")
	proto.RegisterType((*ContentResponse)(nil), "ContentResponse")
	proto.RegisterEnum("ContentType", ContentType_name, ContentType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContentWorkflowClient is the client API for ContentWorkflow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContentWorkflowClient interface {
	New(ctx context.Context, in *ContentRequest, opts ...grpc.CallOption) (*ContentResponse, error)
	Get(ctx context.Context, in *ContentRequest, opts ...grpc.CallOption) (*ContentResponse, error)
	List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (ContentWorkflow_ListClient, error)
}

type contentWorkflowClient struct {
	cc *grpc.ClientConn
}

func NewContentWorkflowClient(cc *grpc.ClientConn) ContentWorkflowClient {
	return &contentWorkflowClient{cc}
}

func (c *contentWorkflowClient) New(ctx context.Context, in *ContentRequest, opts ...grpc.CallOption) (*ContentResponse, error) {
	out := new(ContentResponse)
	err := c.cc.Invoke(ctx, "/ContentWorkflow/New", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentWorkflowClient) Get(ctx context.Context, in *ContentRequest, opts ...grpc.CallOption) (*ContentResponse, error) {
	out := new(ContentResponse)
	err := c.cc.Invoke(ctx, "/ContentWorkflow/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contentWorkflowClient) List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (ContentWorkflow_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ContentWorkflow_serviceDesc.Streams[0], "/ContentWorkflow/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &contentWorkflowListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ContentWorkflow_ListClient interface {
	Recv() (*ContentResponse, error)
	grpc.ClientStream
}

type contentWorkflowListClient struct {
	grpc.ClientStream
}

func (x *contentWorkflowListClient) Recv() (*ContentResponse, error) {
	m := new(ContentResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ContentWorkflowServer is the server API for ContentWorkflow service.
type ContentWorkflowServer interface {
	New(context.Context, *ContentRequest) (*ContentResponse, error)
	Get(context.Context, *ContentRequest) (*ContentResponse, error)
	List(*empty.Empty, ContentWorkflow_ListServer) error
}

func RegisterContentWorkflowServer(s *grpc.Server, srv ContentWorkflowServer) {
	s.RegisterService(&_ContentWorkflow_serviceDesc, srv)
}

func _ContentWorkflow_New_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentWorkflowServer).New(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentWorkflow/New",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentWorkflowServer).New(ctx, req.(*ContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentWorkflow_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContentWorkflowServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ContentWorkflow/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContentWorkflowServer).Get(ctx, req.(*ContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContentWorkflow_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ContentWorkflowServer).List(m, &contentWorkflowListServer{stream})
}

type ContentWorkflow_ListServer interface {
	Send(*ContentResponse) error
	grpc.ServerStream
}

type contentWorkflowListServer struct {
	grpc.ServerStream
}

func (x *contentWorkflowListServer) Send(m *ContentResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ContentWorkflow_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ContentWorkflow",
	HandlerType: (*ContentWorkflowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "New",
			Handler:    _ContentWorkflow_New_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ContentWorkflow_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _ContentWorkflow_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "content_workflow.proto3",
}

func init() {
	proto.RegisterFile("content_workflow.proto3", fileDescriptor_content_workflow_f08798b923403014)
}

var fileDescriptor_content_workflow_f08798b923403014 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0xce, 0xcf, 0x2b,
	0x49, 0xcd, 0x2b, 0x89, 0x2f, 0xcf, 0x2f, 0xca, 0x4e, 0xcb, 0xc9, 0x2f, 0xd7, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x37, 0x96, 0x92, 0x4e, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x73, 0x93, 0x4a,
	0xd3, 0xf4, 0x53, 0x73, 0x0b, 0x4a, 0x2a, 0x21, 0xb2, 0x4a, 0x61, 0x5c, 0x7c, 0xce, 0x10, 0x7d,
	0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0xcc, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x02, 0x17, 0x4b, 0x49, 0x65, 0x41, 0xaa,
	0x04, 0xb3, 0x02, 0xa3, 0x06, 0x9f, 0x11, 0x8f, 0x1e, 0xd4, 0x88, 0x90, 0xca, 0x82, 0xd4, 0x20,
	0xb0, 0x8c, 0x52, 0x0c, 0x17, 0x3f, 0xdc, 0xdc, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x0c, 0x83,
	0x25, 0xb8, 0xd8, 0xa1, 0x4e, 0x86, 0x9a, 0x0d, 0xe3, 0x0a, 0xc9, 0x73, 0x71, 0xc3, 0x3c, 0x53,
	0x5a, 0x94, 0x03, 0xb6, 0x85, 0x33, 0x88, 0x0b, 0x2a, 0x14, 0x5a, 0x94, 0xa3, 0xa5, 0xc9, 0xc5,
	0x8d, 0x64, 0xa5, 0x90, 0x14, 0x97, 0x98, 0xaf, 0x63, 0x90, 0xb7, 0x6b, 0x88, 0xa7, 0x9f, 0x7b,
	0xbc, 0x8f, 0xa3, 0x9f, 0x0b, 0x88, 0x0e, 0x70, 0x74, 0x77, 0x15, 0x60, 0x30, 0x9a, 0xcf, 0x08,
	0x77, 0x49, 0x38, 0x34, 0x60, 0x84, 0xb4, 0xb8, 0x98, 0xfd, 0x52, 0xcb, 0x85, 0xf8, 0xf5, 0x50,
	0xbd, 0x2e, 0x25, 0xa0, 0x87, 0xe6, 0x66, 0x25, 0x06, 0x90, 0x5a, 0xf7, 0xd4, 0x12, 0xe2, 0xd4,
	0x9a, 0x70, 0xb1, 0xf8, 0x64, 0x16, 0x97, 0x08, 0x89, 0xe9, 0x41, 0x82, 0x5c, 0x0f, 0x16, 0xe4,
	0x7a, 0xae, 0xa0, 0x20, 0xc7, 0xa6, 0xc7, 0x80, 0x31, 0x89, 0x0d, 0x12, 0x4f, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xb1, 0x53, 0xe4, 0xe4, 0xc1, 0x01, 0x00, 0x00,
}
