// Code generated by protoc-gen-go. DO NOT EDIT.
// source: action_workflow.proto3

package workflow

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ActionRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionRequest) Reset()         { *m = ActionRequest{} }
func (m *ActionRequest) String() string { return proto.CompactTextString(m) }
func (*ActionRequest) ProtoMessage()    {}
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_799effcaa39adcce, []int{0}
}

func (m *ActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionRequest.Unmarshal(m, b)
}
func (m *ActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionRequest.Marshal(b, m, deterministic)
}
func (m *ActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionRequest.Merge(m, src)
}
func (m *ActionRequest) XXX_Size() int {
	return xxx_messageInfo_ActionRequest.Size(m)
}
func (m *ActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActionRequest proto.InternalMessageInfo

func (m *ActionRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ActionResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActionResponse) Reset()         { *m = ActionResponse{} }
func (m *ActionResponse) String() string { return proto.CompactTextString(m) }
func (*ActionResponse) ProtoMessage()    {}
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_799effcaa39adcce, []int{1}
}

func (m *ActionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActionResponse.Unmarshal(m, b)
}
func (m *ActionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActionResponse.Marshal(b, m, deterministic)
}
func (m *ActionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActionResponse.Merge(m, src)
}
func (m *ActionResponse) XXX_Size() int {
	return xxx_messageInfo_ActionResponse.Size(m)
}
func (m *ActionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActionResponse proto.InternalMessageInfo

func (m *ActionResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ActionRequest)(nil), "ActionRequest")
	proto.RegisterType((*ActionResponse)(nil), "ActionResponse")
}

func init() { proto.RegisterFile("action_workflow.proto3", fileDescriptor_799effcaa39adcce) }

var fileDescriptor_799effcaa39adcce = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x4c, 0x2e, 0xc9,
	0xcc, 0xcf, 0x8b, 0x2f, 0xcf, 0x2f, 0xca, 0x4e, 0xcb, 0xc9, 0x2f, 0xd7, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x37, 0x96, 0x92, 0x4e, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x73, 0x93, 0x4a, 0xd3,
	0xf4, 0x53, 0x73, 0x0b, 0x4a, 0x2a, 0x21, 0xb2, 0x4a, 0xca, 0x5c, 0xbc, 0x8e, 0x60, 0x6d, 0x41,
	0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c,
	0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92, 0x16, 0x17, 0x1f, 0x4c, 0x51, 0x71, 0x41, 0x7e,
	0x5e, 0x71, 0xaa, 0x90, 0x04, 0x17, 0x7b, 0x6e, 0x6a, 0x71, 0x71, 0x62, 0x3a, 0x4c, 0x21, 0x8c,
	0x6b, 0x34, 0x93, 0x11, 0xa6, 0x38, 0x1c, 0xea, 0x0e, 0x21, 0x0d, 0x2e, 0x66, 0xbf, 0xd4, 0x72,
	0x21, 0x3e, 0x3d, 0x14, 0x9b, 0xa4, 0xf8, 0xf5, 0x50, 0x0d, 0x55, 0x62, 0x00, 0xa9, 0x74, 0x4f,
	0x2d, 0x21, 0x46, 0xa5, 0x31, 0x17, 0x8b, 0x4f, 0x66, 0x71, 0x89, 0x90, 0x98, 0x1e, 0xc4, 0x77,
	0x7a, 0x30, 0xdf, 0xe9, 0xb9, 0x82, 0x7c, 0x87, 0x45, 0x8b, 0x01, 0x63, 0x12, 0x1b, 0x24, 0x44,
	0x00, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc6, 0xf0, 0xa7, 0x0e, 0x2a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ActionWorkflowClient is the client API for ActionWorkflow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ActionWorkflowClient interface {
	New(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	Get(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error)
	List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (ActionWorkflow_ListClient, error)
}

type actionWorkflowClient struct {
	cc *grpc.ClientConn
}

func NewActionWorkflowClient(cc *grpc.ClientConn) ActionWorkflowClient {
	return &actionWorkflowClient{cc}
}

func (c *actionWorkflowClient) New(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, "/ActionWorkflow/New", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionWorkflowClient) Get(ctx context.Context, in *ActionRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, "/ActionWorkflow/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionWorkflowClient) List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (ActionWorkflow_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ActionWorkflow_serviceDesc.Streams[0], "/ActionWorkflow/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &actionWorkflowListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ActionWorkflow_ListClient interface {
	Recv() (*ActionResponse, error)
	grpc.ClientStream
}

type actionWorkflowListClient struct {
	grpc.ClientStream
}

func (x *actionWorkflowListClient) Recv() (*ActionResponse, error) {
	m := new(ActionResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ActionWorkflowServer is the server API for ActionWorkflow service.
type ActionWorkflowServer interface {
	New(context.Context, *ActionRequest) (*ActionResponse, error)
	Get(context.Context, *ActionRequest) (*ActionResponse, error)
	List(*empty.Empty, ActionWorkflow_ListServer) error
}

func RegisterActionWorkflowServer(s *grpc.Server, srv ActionWorkflowServer) {
	s.RegisterService(&_ActionWorkflow_serviceDesc, srv)
}

func _ActionWorkflow_New_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionWorkflowServer).New(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ActionWorkflow/New",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionWorkflowServer).New(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionWorkflow_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionWorkflowServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ActionWorkflow/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionWorkflowServer).Get(ctx, req.(*ActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionWorkflow_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ActionWorkflowServer).List(m, &actionWorkflowListServer{stream})
}

type ActionWorkflow_ListServer interface {
	Send(*ActionResponse) error
	grpc.ServerStream
}

type actionWorkflowListServer struct {
	grpc.ServerStream
}

func (x *actionWorkflowListServer) Send(m *ActionResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ActionWorkflow_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ActionWorkflow",
	HandlerType: (*ActionWorkflowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "New",
			Handler:    _ActionWorkflow_New_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ActionWorkflow_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _ActionWorkflow_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "action_workflow.proto3",
}
