// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app_workflow.proto3

package workflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AppWorkflowBody struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppWorkflowBody) Reset()         { *m = AppWorkflowBody{} }
func (m *AppWorkflowBody) String() string { return proto.CompactTextString(m) }
func (*AppWorkflowBody) ProtoMessage()    {}
func (*AppWorkflowBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_app_workflow_5c8afac886afb2b4, []int{0}
}
func (m *AppWorkflowBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppWorkflowBody.Unmarshal(m, b)
}
func (m *AppWorkflowBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppWorkflowBody.Marshal(b, m, deterministic)
}
func (dst *AppWorkflowBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppWorkflowBody.Merge(dst, src)
}
func (m *AppWorkflowBody) XXX_Size() int {
	return xxx_messageInfo_AppWorkflowBody.Size(m)
}
func (m *AppWorkflowBody) XXX_DiscardUnknown() {
	xxx_messageInfo_AppWorkflowBody.DiscardUnknown(m)
}

var xxx_messageInfo_AppWorkflowBody proto.InternalMessageInfo

func init() {
	proto.RegisterType((*AppWorkflowBody)(nil), "AppWorkflowBody")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppWorkflowClient is the client API for AppWorkflow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppWorkflowClient interface {
	Invoke(ctx context.Context, in *AppWorkflowBody, opts ...grpc.CallOption) (*AppWorkflowBody, error)
}

type appWorkflowClient struct {
	cc *grpc.ClientConn
}

func NewAppWorkflowClient(cc *grpc.ClientConn) AppWorkflowClient {
	return &appWorkflowClient{cc}
}

func (c *appWorkflowClient) Invoke(ctx context.Context, in *AppWorkflowBody, opts ...grpc.CallOption) (*AppWorkflowBody, error) {
	out := new(AppWorkflowBody)
	err := c.cc.Invoke(ctx, "/AppWorkflow/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppWorkflowServer is the server API for AppWorkflow service.
type AppWorkflowServer interface {
	Invoke(context.Context, *AppWorkflowBody) (*AppWorkflowBody, error)
}

func RegisterAppWorkflowServer(s *grpc.Server, srv AppWorkflowServer) {
	s.RegisterService(&_AppWorkflow_serviceDesc, srv)
}

func _AppWorkflow_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppWorkflowBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppWorkflowServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AppWorkflow/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppWorkflowServer).Invoke(ctx, req.(*AppWorkflowBody))
	}
	return interceptor(ctx, in, info, handler)
}

var _AppWorkflow_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AppWorkflow",
	HandlerType: (*AppWorkflowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _AppWorkflow_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app_workflow.proto3",
}

func init() { proto.RegisterFile("app_workflow.proto3", fileDescriptor_app_workflow_5c8afac886afb2b4) }

var fileDescriptor_app_workflow_5c8afac886afb2b4 = []byte{
	// 89 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x2c, 0x28, 0x88,
	0x2f, 0xcf, 0x2f, 0xca, 0x4e, 0xcb, 0xc9, 0x2f, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x37, 0x56,
	0x12, 0xe4, 0xe2, 0x77, 0x2c, 0x28, 0x08, 0x87, 0x8a, 0x3a, 0xe5, 0xa7, 0x54, 0x1a, 0xd9, 0x72,
	0x71, 0x23, 0x09, 0x09, 0xe9, 0x71, 0xb1, 0x79, 0xe6, 0x95, 0xe5, 0x67, 0xa7, 0x0a, 0x09, 0xe8,
	0xa1, 0x29, 0x95, 0xc2, 0x10, 0x51, 0x62, 0x48, 0x62, 0x83, 0x98, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0x5c, 0x2c, 0xd9, 0xc2, 0x6f, 0x00, 0x00, 0x00,
}
