// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data_workflow.proto3

package workflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DataType int32

const (
	DataType_Collect DataType = 0
	DataType_Clean   DataType = 1
)

var DataType_name = map[int32]string{
	0: "Collect",
	1: "Clean",
}
var DataType_value = map[string]int32{
	"Collect": 0,
	"Clean":   1,
}

func (x DataType) String() string {
	return proto.EnumName(DataType_name, int32(x))
}
func (DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_data_workflow_e66d3fd4d2e3713b, []int{0}
}

type DataRequest struct {
	Type                 DataType `protobuf:"varint,1,opt,name=type,proto3,enum=DataType" json:"type,omitempty"`
	Identifier           string   `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRequest) Reset()         { *m = DataRequest{} }
func (m *DataRequest) String() string { return proto.CompactTextString(m) }
func (*DataRequest) ProtoMessage()    {}
func (*DataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_workflow_e66d3fd4d2e3713b, []int{0}
}
func (m *DataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRequest.Unmarshal(m, b)
}
func (m *DataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRequest.Marshal(b, m, deterministic)
}
func (dst *DataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRequest.Merge(dst, src)
}
func (m *DataRequest) XXX_Size() int {
	return xxx_messageInfo_DataRequest.Size(m)
}
func (m *DataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DataRequest proto.InternalMessageInfo

func (m *DataRequest) GetType() DataType {
	if m != nil {
		return m.Type
	}
	return DataType_Collect
}

func (m *DataRequest) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

type DataResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataResponse) Reset()         { *m = DataResponse{} }
func (m *DataResponse) String() string { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()    {}
func (*DataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_data_workflow_e66d3fd4d2e3713b, []int{1}
}
func (m *DataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse.Unmarshal(m, b)
}
func (m *DataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse.Marshal(b, m, deterministic)
}
func (dst *DataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse.Merge(dst, src)
}
func (m *DataResponse) XXX_Size() int {
	return xxx_messageInfo_DataResponse.Size(m)
}
func (m *DataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse proto.InternalMessageInfo

func (m *DataResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*DataRequest)(nil), "DataRequest")
	proto.RegisterType((*DataResponse)(nil), "DataResponse")
	proto.RegisterEnum("DataType", DataType_name, DataType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataWorkflowClient is the client API for DataWorkflow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataWorkflowClient interface {
	New(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error)
	Get(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error)
	List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (DataWorkflow_ListClient, error)
}

type dataWorkflowClient struct {
	cc *grpc.ClientConn
}

func NewDataWorkflowClient(cc *grpc.ClientConn) DataWorkflowClient {
	return &dataWorkflowClient{cc}
}

func (c *dataWorkflowClient) New(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/DataWorkflow/New", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataWorkflowClient) Get(ctx context.Context, in *DataRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/DataWorkflow/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataWorkflowClient) List(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (DataWorkflow_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DataWorkflow_serviceDesc.Streams[0], "/DataWorkflow/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &dataWorkflowListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DataWorkflow_ListClient interface {
	Recv() (*DataResponse, error)
	grpc.ClientStream
}

type dataWorkflowListClient struct {
	grpc.ClientStream
}

func (x *dataWorkflowListClient) Recv() (*DataResponse, error) {
	m := new(DataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DataWorkflowServer is the server API for DataWorkflow service.
type DataWorkflowServer interface {
	New(context.Context, *DataRequest) (*DataResponse, error)
	Get(context.Context, *DataRequest) (*DataResponse, error)
	List(*empty.Empty, DataWorkflow_ListServer) error
}

func RegisterDataWorkflowServer(s *grpc.Server, srv DataWorkflowServer) {
	s.RegisterService(&_DataWorkflow_serviceDesc, srv)
}

func _DataWorkflow_New_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataWorkflowServer).New(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DataWorkflow/New",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataWorkflowServer).New(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataWorkflow_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataWorkflowServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/DataWorkflow/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataWorkflowServer).Get(ctx, req.(*DataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataWorkflow_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataWorkflowServer).List(m, &dataWorkflowListServer{stream})
}

type DataWorkflow_ListServer interface {
	Send(*DataResponse) error
	grpc.ServerStream
}

type dataWorkflowListServer struct {
	grpc.ServerStream
}

func (x *dataWorkflowListServer) Send(m *DataResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _DataWorkflow_serviceDesc = grpc.ServiceDesc{
	ServiceName: "DataWorkflow",
	HandlerType: (*DataWorkflowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "New",
			Handler:    _DataWorkflow_New_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DataWorkflow_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _DataWorkflow_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "data_workflow.proto3",
}

func init() { proto.RegisterFile("data_workflow.proto3", fileDescriptor_data_workflow_e66d3fd4d2e3713b) }

var fileDescriptor_data_workflow_e66d3fd4d2e3713b = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xbb, 0x5a, 0xad, 0x99, 0x56, 0x29, 0x8b, 0x48, 0xa8, 0x28, 0x25, 0x78, 0x08, 0x1e,
	0xb6, 0x5a, 0x1f, 0xa1, 0x8a, 0x97, 0xe2, 0x21, 0x08, 0x1e, 0x65, 0x6b, 0x27, 0x21, 0xb8, 0xcd,
	0xac, 0xd9, 0x29, 0x21, 0x0f, 0xe1, 0x3b, 0x4b, 0xb2, 0x06, 0x02, 0x1e, 0x3c, 0xce, 0xfc, 0xff,
	0x7e, 0xbb, 0xfb, 0xc1, 0xf9, 0x56, 0xb3, 0x7e, 0xaf, 0xa8, 0xfc, 0x4c, 0x0d, 0x55, 0xca, 0x96,
	0xc4, 0xf4, 0x30, 0xbb, 0xcc, 0x88, 0x32, 0x83, 0x8b, 0x76, 0xdc, 0xec, 0xd3, 0x05, 0xee, 0x2c,
	0xd7, 0x3e, 0x8d, 0xd6, 0x30, 0x7e, 0xd4, 0xac, 0x13, 0xfc, 0xda, 0xa3, 0x63, 0x79, 0x05, 0x43,
	0xae, 0x2d, 0x86, 0x62, 0x2e, 0xe2, 0xb3, 0x65, 0xa0, 0x9a, 0xec, 0xb5, 0xb6, 0x98, 0xb4, 0x6b,
	0x79, 0x0d, 0x90, 0x6f, 0xb1, 0xe0, 0x3c, 0xcd, 0xb1, 0x0c, 0x0f, 0xe6, 0x22, 0x0e, 0x92, 0xde,
	0x26, 0x8a, 0x61, 0xe2, 0x69, 0xce, 0x52, 0xe1, 0x50, 0x86, 0x30, 0xda, 0xa1, 0x73, 0x3a, 0xf3,
	0xc4, 0x20, 0xe9, 0xc6, 0xdb, 0x08, 0x4e, 0x3a, 0xb6, 0x1c, 0xc3, 0x68, 0x45, 0xc6, 0xe0, 0x07,
	0x4f, 0x07, 0x32, 0x80, 0xa3, 0x95, 0x41, 0x5d, 0x4c, 0xc5, 0xf2, 0x5b, 0x78, 0xdc, 0xdb, 0xef,
	0x87, 0xe4, 0x0d, 0x1c, 0xbe, 0x60, 0x25, 0x27, 0xaa, 0xf7, 0xe4, 0xd9, 0xa9, 0xea, 0x5f, 0x19,
	0x0d, 0x9a, 0xd6, 0x33, 0xf2, 0x7f, 0xad, 0x7b, 0x18, 0xae, 0x73, 0xc7, 0xf2, 0x42, 0x79, 0x3d,
	0xaa, 0xd3, 0xa3, 0x9e, 0x1a, 0x3d, 0x7f, 0x0e, 0xdc, 0x89, 0xcd, 0xb1, 0x17, 0xfa, 0x13, 0x00,
	0x00, 0xff, 0xff, 0x22, 0xaa, 0x2f, 0x16, 0x67, 0x01, 0x00, 0x00,
}
