// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fields.proto3

package workflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FieldType int32

const (
	FieldType_LongText  FieldType = 0
	FieldType_ShortText FieldType = 1
	FieldType_Select    FieldType = 2
	FieldType_Radio     FieldType = 3
	FieldType_Hidden    FieldType = 4
	FieldType_Label     FieldType = 5
	FieldType_Image     FieldType = 6
	FieldType_JSON      FieldType = 7
)

var FieldType_name = map[int32]string{
	0: "LongText",
	1: "ShortText",
	2: "Select",
	3: "Radio",
	4: "Hidden",
	5: "Label",
	6: "Image",
	7: "JSON",
}
var FieldType_value = map[string]int32{
	"LongText":  0,
	"ShortText": 1,
	"Select":    2,
	"Radio":     3,
	"Hidden":    4,
	"Label":     5,
	"Image":     6,
	"JSON":      7,
}

func (x FieldType) String() string {
	return proto.EnumName(FieldType_name, int32(x))
}
func (FieldType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fields_f7e38b8959064476, []int{0}
}

type Field struct {
	Name                 string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Type                 FieldType `protobuf:"varint,2,opt,name=Type,proto3,enum=FieldType" json:"Type,omitempty"`
	Value                string    `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	Instructions         string    `protobuf:"bytes,4,opt,name=Instructions,proto3" json:"Instructions,omitempty"`
	Options              []string  `protobuf:"bytes,5,rep,name=Options,proto3" json:"Options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_fields_f7e38b8959064476, []int{0}
}
func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (dst *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(dst, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetType() FieldType {
	if m != nil {
		return m.Type
	}
	return FieldType_LongText
}

func (m *Field) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Field) GetInstructions() string {
	if m != nil {
		return m.Instructions
	}
	return ""
}

func (m *Field) GetOptions() []string {
	if m != nil {
		return m.Options
	}
	return nil
}

func init() {
	proto.RegisterType((*Field)(nil), "Field")
	proto.RegisterEnum("FieldType", FieldType_name, FieldType_value)
}

func init() { proto.RegisterFile("fields.proto3", fileDescriptor_fields_f7e38b8959064476) }

var fileDescriptor_fields_f7e38b8959064476 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x4d, 0x37, 0xd9, 0x36, 0x43, 0x2b, 0x61, 0xf0, 0x90, 0x93, 0x2c, 0x3d, 0x2d, 0x1e,
	0x7a, 0xd0, 0x77, 0x10, 0x2b, 0xa5, 0x85, 0xdd, 0xe2, 0x3d, 0xed, 0x8e, 0x75, 0x31, 0x4d, 0x96,
	0xdd, 0x14, 0xf4, 0x29, 0x7c, 0x65, 0x49, 0x16, 0x85, 0xde, 0xfe, 0xef, 0xfb, 0x67, 0x18, 0x18,
	0x58, 0xbc, 0xb7, 0x64, 0x9b, 0x61, 0xd5, 0xf5, 0x3e, 0xf8, 0xa7, 0xe5, 0x0f, 0x03, 0xf1, 0x1c,
	0x0d, 0x22, 0xf0, 0xad, 0x39, 0x93, 0x66, 0x05, 0x2b, 0x65, 0x95, 0x32, 0xde, 0x03, 0xdf, 0x7f,
	0x77, 0xa4, 0x27, 0x05, 0x2b, 0x6f, 0x1f, 0x61, 0x95, 0x26, 0xa3, 0xa9, 0x92, 0xc7, 0x3b, 0x10,
	0x6f, 0xc6, 0x5e, 0x48, 0x67, 0x69, 0x69, 0x04, 0x5c, 0xc2, 0x7c, 0xed, 0x86, 0xd0, 0x5f, 0x8e,
	0xa1, 0xf5, 0x6e, 0xd0, 0x3c, 0x95, 0x57, 0x0e, 0x35, 0x4c, 0x77, 0xdd, 0x58, 0x8b, 0x22, 0x2b,
	0x65, 0xf5, 0x87, 0x0f, 0x9f, 0x20, 0xff, 0xcf, 0xe0, 0x1c, 0x66, 0x1b, 0xef, 0x4e, 0x7b, 0xfa,
	0x0a, 0xea, 0x06, 0x17, 0x20, 0xeb, 0x0f, 0xdf, 0x87, 0x84, 0x0c, 0x01, 0xf2, 0x9a, 0x2c, 0x1d,
	0x83, 0x9a, 0xa0, 0x04, 0x51, 0x99, 0xa6, 0xf5, 0x2a, 0x8b, 0xfa, 0xa5, 0x6d, 0x1a, 0x72, 0x8a,
	0x47, 0xbd, 0x31, 0x07, 0xb2, 0x4a, 0xc4, 0xb8, 0x3e, 0x9b, 0x13, 0xa9, 0x1c, 0x67, 0xc0, 0x5f,
	0xeb, 0xdd, 0x56, 0x4d, 0x0f, 0xf9, 0xf8, 0x86, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x45, 0x95,
	0xb5, 0xcb, 0x16, 0x01, 0x00, 0x00,
}
