// Code generated by protoc-gen-go. DO NOT EDIT.
// source: landingcrew.proto3

package workflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("landingcrew.proto3", fileDescriptor_landingcrew_33f34386f6b6c790) }

var fileDescriptor_landingcrew_33f34386f6b6c790 = []byte{
	// 60 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0x49, 0xcc, 0x4b,
	0xc9, 0xcc, 0x4b, 0x4f, 0x2e, 0x4a, 0x2d, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x37, 0x76, 0xe2,
	0x8a, 0xe2, 0x28, 0xcf, 0x2f, 0xca, 0x4e, 0xcb, 0xc9, 0x2f, 0x4f, 0x62, 0x83, 0x88, 0x01, 0x02,
	0x00, 0x00, 0xff, 0xff, 0xe9, 0x09, 0x5f, 0x6d, 0x28, 0x00, 0x00, 0x00,
}
