// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto3

package workflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TaskBody struct {
	Id                   int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields               []*Field          `protobuf:"bytes,2,rep,name=Fields,proto3" json:"Fields,omitempty"`
	Environment          map[string]string `protobuf:"bytes,3,rep,name=Environment,proto3" json:"Environment,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	State                State             `protobuf:"varint,4,opt,name=State,proto3,enum=State" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TaskBody) Reset()         { *m = TaskBody{} }
func (m *TaskBody) String() string { return proto.CompactTextString(m) }
func (*TaskBody) ProtoMessage()    {}
func (*TaskBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_85c19d6e911963d6, []int{0}
}
func (m *TaskBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskBody.Unmarshal(m, b)
}
func (m *TaskBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskBody.Marshal(b, m, deterministic)
}
func (dst *TaskBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskBody.Merge(dst, src)
}
func (m *TaskBody) XXX_Size() int {
	return xxx_messageInfo_TaskBody.Size(m)
}
func (m *TaskBody) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskBody.DiscardUnknown(m)
}

var xxx_messageInfo_TaskBody proto.InternalMessageInfo

func (m *TaskBody) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TaskBody) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *TaskBody) GetEnvironment() map[string]string {
	if m != nil {
		return m.Environment
	}
	return nil
}

func (m *TaskBody) GetState() State {
	if m != nil {
		return m.State
	}
	return State_Idle
}

func init() {
	proto.RegisterType((*TaskBody)(nil), "TaskBody")
	proto.RegisterMapType((map[string]string)(nil), "TaskBody.EnvironmentEntry")
}

func init() { proto.RegisterFile("task.proto3", fileDescriptor_task_85c19d6e911963d6) }

var fileDescriptor_task_85c19d6e911963d6 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x49, 0x2c, 0xce,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x37, 0x96, 0xe2, 0x4d, 0xcb, 0x4c, 0xcd, 0x49, 0x29, 0x86,
	0x71, 0x79, 0x8a, 0x4b, 0x12, 0x4b, 0x52, 0xa1, 0x3c, 0xa5, 0x6b, 0x8c, 0x5c, 0x1c, 0x21, 0x89,
	0xc5, 0xd9, 0x4e, 0xf9, 0x29, 0x95, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0xcc, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x72, 0x5c, 0x6c, 0x6e, 0x60, 0xbd, 0x12, 0x4c, 0x0a,
	0xcc, 0x1a, 0xdc, 0x46, 0x6c, 0x7a, 0x60, 0x6e, 0x10, 0x54, 0x54, 0xc8, 0x86, 0x8b, 0xdb, 0x35,
	0xaf, 0x2c, 0xb3, 0x28, 0x3f, 0x2f, 0x37, 0x35, 0xaf, 0x44, 0x82, 0x19, 0xac, 0x48, 0x4a, 0x0f,
	0x66, 0x9e, 0x1e, 0x92, 0xa4, 0x6b, 0x5e, 0x49, 0x51, 0x65, 0x10, 0xb2, 0x72, 0x21, 0x19, 0x2e,
	0xd6, 0x60, 0x90, 0x53, 0x24, 0x58, 0x14, 0x18, 0x35, 0xf8, 0x8c, 0xd8, 0xf4, 0xc0, 0xbc, 0x20,
	0x88, 0xa0, 0x94, 0x1d, 0x97, 0x00, 0xba, 0x76, 0x21, 0x01, 0x2e, 0xe6, 0xec, 0xd4, 0x4a, 0xb0,
	0x03, 0x39, 0x83, 0x40, 0x4c, 0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x26,
	0xb0, 0x18, 0x84, 0x63, 0xc5, 0x64, 0xc1, 0x98, 0xc4, 0x06, 0xf1, 0x20, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x38, 0xc7, 0x7a, 0xb9, 0x0b, 0x01, 0x00, 0x00,
}
