// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto3

package workflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TaskBody struct {
	Identifier           string            `protobuf:"bytes,1,opt,name=Identifier,proto3" json:"Identifier,omitempty"`
	Fields               []*Field          `protobuf:"bytes,2,rep,name=Fields,proto3" json:"Fields,omitempty"`
	Environment          map[string]string `protobuf:"bytes,3,rep,name=Environment,proto3" json:"Environment,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	State                State             `protobuf:"varint,4,opt,name=State,proto3,enum=State" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TaskBody) Reset()         { *m = TaskBody{} }
func (m *TaskBody) String() string { return proto.CompactTextString(m) }
func (*TaskBody) ProtoMessage()    {}
func (*TaskBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_task_66faaeaea9ffb510, []int{0}
}
func (m *TaskBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskBody.Unmarshal(m, b)
}
func (m *TaskBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskBody.Marshal(b, m, deterministic)
}
func (dst *TaskBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskBody.Merge(dst, src)
}
func (m *TaskBody) XXX_Size() int {
	return xxx_messageInfo_TaskBody.Size(m)
}
func (m *TaskBody) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskBody.DiscardUnknown(m)
}

var xxx_messageInfo_TaskBody proto.InternalMessageInfo

func (m *TaskBody) GetIdentifier() string {
	if m != nil {
		return m.Identifier
	}
	return ""
}

func (m *TaskBody) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *TaskBody) GetEnvironment() map[string]string {
	if m != nil {
		return m.Environment
	}
	return nil
}

func (m *TaskBody) GetState() State {
	if m != nil {
		return m.State
	}
	return State_Idle
}

func init() {
	proto.RegisterType((*TaskBody)(nil), "TaskBody")
	proto.RegisterMapType((map[string]string)(nil), "TaskBody.EnvironmentEntry")
}

func init() { proto.RegisterFile("task.proto3", fileDescriptor_task_66faaeaea9ffb510) }

var fileDescriptor_task_66faaeaea9ffb510 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x49, 0x2c, 0xce,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x37, 0x96, 0xe2, 0x4d, 0xcb, 0x4c, 0xcd, 0x49, 0x29, 0x86,
	0x71, 0x79, 0x8a, 0x4b, 0x12, 0x4b, 0x52, 0xa1, 0x3c, 0xa5, 0x67, 0x8c, 0x5c, 0x1c, 0x21, 0x89,
	0xc5, 0xd9, 0x4e, 0xf9, 0x29, 0x95, 0x42, 0x72, 0x5c, 0x5c, 0x9e, 0x29, 0xa9, 0x79, 0x25, 0x99,
	0x69, 0x99, 0xa9, 0x45, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x48, 0x22, 0x42, 0x72, 0x5c,
	0x6c, 0x6e, 0x60, 0xb3, 0x24, 0x98, 0x14, 0x98, 0x35, 0xb8, 0x8d, 0xd8, 0xf4, 0xc0, 0xdc, 0x20,
	0xa8, 0xa8, 0x90, 0x0d, 0x17, 0xb7, 0x6b, 0x5e, 0x59, 0x66, 0x51, 0x7e, 0x5e, 0x6e, 0x6a, 0x5e,
	0x89, 0x04, 0x33, 0x58, 0x91, 0x94, 0x1e, 0xcc, 0x7c, 0x3d, 0x24, 0x49, 0xd7, 0xbc, 0x92, 0xa2,
	0xca, 0x20, 0x64, 0xe5, 0x42, 0x32, 0x5c, 0xac, 0xc1, 0x20, 0xa7, 0x49, 0xb0, 0x28, 0x30, 0x6a,
	0xf0, 0x19, 0xb1, 0xe9, 0x81, 0x79, 0x41, 0x10, 0x41, 0x29, 0x3b, 0x2e, 0x01, 0x74, 0xed, 0x42,
	0x02, 0x5c, 0xcc, 0xd9, 0xa9, 0x95, 0x50, 0x87, 0x82, 0x98, 0x42, 0x22, 0x5c, 0xac, 0x65, 0x89,
	0x39, 0xa5, 0xa9, 0x12, 0x4c, 0x60, 0x31, 0x08, 0xc7, 0x8a, 0xc9, 0x82, 0x31, 0x89, 0x0d, 0xe2,
	0x61, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x22, 0x18, 0x64, 0x1b, 0x01, 0x00, 0x00,
}
